---
# author = "Sawan Choudhary"
# copyright = "Copyright 2017, CalsoftInc"
# maintainer = "Calsoft IT"

- hosts: esxi
  become: yes

  tasks:
  - name: include vars
    include_vars: dict_from_csv.py

  - name: Power on vm
    vsphere_guest:
      vcenter_hostname: 172.17.xx.xx
      username: xxxx
      password: xxxxxxxxxx
      guest: "{{gen_info[5]}}"
      state: powered_on
      validate_certs: False
      esxi:
        datacenter: ha-datacenter
        hostname: localhost.localdomain

  - name: Wait for vm to start
    pause: seconds=120

